### ISSUE TITLE
Endless blink

### ISSUE THREAD

**Issue by KitesAir** [AchimPieters/ESP8266-HomeKit-Temperature-Humidity-Sensor#2]
Hi Achim Pieters,

Please check the main11.bin. After flashing, I tried to reset but can't find the AP and the light is endless blinked. Please check and help me. Thanks in advanced 👍

**Comment by AchimPieters** [comment]
@KitesAir did you reset after uploading LCM to your device?

**Comment by KitesAir** [comment]
@AchimPieters Yes. Of course. I tried to reset it by reset button and turn off/turn on as well, but it is still not working :(

**Comment by AchimPieters** [comment]
@KitesAir what you can do is to use the serial monitor from the Arduino IDE, this will show you what's happening on your esp device.

**Comment by KitesAir** [comment]
@AchimPieters It loops all these message :(

ESP-Open-SDK ver: 0.0.1 compiled @ May 23 2019 16:48:22
phy ver: 273, pp ver: 8.3

mode : softAP(12:52:1c:02:d1:cf)
add if1
bcn 100
Couldnt read data from sensor
>>> HomeKit: Starting server
>>> HomeKit: Using existing accessory ID: 8C:D9:FA:81:41:37
>>> mDNS_init: wifi opmode not station
>>> HomeKit: Configuring mDNS
rtos assert /opt/esp-open-rtos/FreeRTOS/Source/queue.c 1406
abort() invoked at 0x402048af.

Stack: SP=0x3fff63e0
0x3fff63e0: 00000000 3fff196c 00000000 402048b2
0x3fff63f0: 00000000 00000000 00000000 402050d4
0x3fff6400: 00000008 00000000 00000000 40235708
0x3fff6410: ffffffff 3fff6400 3fff64fc 00000000
0x3fff6420: 00000001 00000000 00000003 40235708
0x3fff6430: 40236cf4 3fff196c 00000000 4021bd92
0x3fff6440: 00000000 3fff6b78 00000000 4021addb
0x3fff6450: 00000000 00000008 00000000 40235708

Free Heap: 38040
_heap_start 0x3fff1d80 brk 0x3fff6b94 supervisor sp 0x40000000 sp-brk 37996 bytes
arena (total_size) 19988 fordblks (free_size) 44 uordblocks (used_size) 19944

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 2292, room 16 
tail 4
chksum 0x57
load 0x3ffe8000, len 772, room 4 
tail 0
chksum 0x0b
csum 0x0b

rBoot v1.4.0 - richardaburton@gmail.com
Flash Size:   8 Mbit
Flash Mode:   DOUT
Flash Speed:  40 MHz
rBoot Option: Big flash
rBoot Option: RTC data

Booting rom 0.
pp_task_hdl : 3fff0000, prio:14, stack:512
pm_task_hdl : 3ffef8f0, prio:1, stack:176
frc2_timer_task_hdl:0x3fff3f00, prio:12, stack:200

**Comment by AchimPieters** [comment]
@KitesAir try doing a `esptool.py erase_flash` and the flash it again.

**Comment by KitesAir** [comment]
Hi @AchimPieters I have tried erase_flash before flash but the same issue. After flashing, the light is blinking again

**Comment by KitesAir** [comment]
> Hi @AchimPieters I have tried erase_flash before flash but the same issue. After flashing, the light is blinking again

Could please you give me all the bin file again?

**Comment by AchimPieters** [comment]
@KitesAir I can do even better here is the source code:

[Archive.zip](https://github.com/AchimPieters/ESP8266-HomeKit-Temperature-Humidity-Sensor/files/5541141/Archive.zip)

**Comment by KitesAir** [comment]
> @KitesAir I can do even better here is the source code:
> 
> [Archive.zip](https://github.com/AchimPieters/ESP8266-HomeKit-Temperature-Humidity-Sensor/files/5541141/Archive.zip)

@AchimPieters Thank you so much. Let me build and try again

**Comment by KitesAir** [comment]
@AchimPieters Thank you very much. It's now working
