### ISSUE TITLE
Failed to pair with homekit accessory kit in home assistant 2020.03.04

### ISSUE THREAD

**Issue by alanv72** [AchimPieters/ESP8266-HomeKit-Temperature-Humidity-Sensor#4]
console from the nodemcuv3 based ESP8266...

dhcp client start...
ip:192.168.1.110,mask:255.255.255.0,gw:192.168.1.1
>>> HomeKit: Got new client connection: 4 from 192.168.1.15
>>> HomeKit: [Client 4] Pair Setup Step 1/3
>>> HomeKit: [Client 4] Pair Setup Step 2/3
!!! HomeKit: [Client 4] Failed to verify peer's proof (code -219)
>>> HomeKit: Got new client connection: 5 from 192.168.1.15
>>> HomeKit: [Client 5] Pair Setup Step 1/3
>>> HomeKit: [Client 5] Refusing to pair: another pairing in progress

Error in home assistant gui...
The device is already pairing with another controller
Abort pairing on all controllers, or try restarting the device, then continue to resume pairing.

BTW.. your guide says pair pin is 12345678, but it appears that is one of the blocked pin in the home assistant integration.. I found the current pin in your .c code of 156-45-568

**Comment by alanv72** [comment]
So it looks like the compiled bin does have the 12345678 as the pin and Homekit was blocking the input and returning "bad pin" blah blah...

I removed 12345678 from the blacklist and it worked! So maybe compile with the 15645568 and update guide?

Thanks for your work.. This has been a fun adventure ;)

I run HA core in a python venv... Commented the 12345678 out of the black list here...
/srv/homeassistant/lib/python3.9/site-packages/homeassistant/components/homekit_controller/config_flow.py  

DISALLOWED_CODES = {
    "00000000",
    "11111111",
    "22222222",
    "33333333",
    "44444444",
    "55555555",
    "66666666",
    "77777777",
    "88888888",
    "99999999",
    "87654321",
}

"""   "12345678", """


From my view.. if you match a blacklisted code, it returns as if the device said it was a bad pin...

def ensure_pin_format(pin):
    """
    Ensure a pin code is correctly formatted.

    Ensures a pin code is in the format 111-11-111. Handles codes with and without dashes.

    If incorrect code is entered, an exception is raised.
    """
    match = PIN_FORMAT.search(pin.strip())
    if not match:
        raise aiohomekit.exceptions.MalformedPinError(f"Invalid PIN code f{pin}")
    pin_without_dashes = "".join(match.groups())
    if pin_without_dashes in DISALLOWED_CODES:
        raise aiohomekit.exceptions.MalformedPinError(f"Invalid PIN code f{pin}")
    return "-".join(match.groups())

**Comment by AchimPieters** [comment]
@alanv72 all is fixed:

 Here you go I made new versions:

Version DHT11 GPIO2 Sensor / GPIO4 LED (dht11_gpio2.bin)

Version DHT11 GPIO4 Sensor / GPIO2 LED (dht11_gpio4.bin)

Version DHT22 GPIO2 Sensor / GPIO4 LED (dht22_gpio2.bin)

Version DHT22 GPIO4 Sensor / GPIO2 LED (dht22_gpio4.bin)
