### ISSUE TITLE
Reset loop after wifi network and OTA repository configuration

### ISSUE THREAD

**Issue by jmcjclark** [AchimPieters/ESP8266-HomeKit-Temperature-Humidity-Sensor#5]
After erasing flash, and flashing the firmware, I am able to configure wifi network and OTA repository. For the OTA repository I used "AchimPieters/ESP8266-HomeKit-Temperature-Humidity-Sensor" and for the OTA binary file I used "dht11_gpio4.bin" The ESP8266 then goes into an endless reboot loop. The serial output is as follows:

--- user_init
--- OTABOOT VERSION: 2.1.2
mode : sta(5c:cf:7f:dc:36:51)
add if0
--- pre_wifi_config
--- ota_read_rtc
--- count_step=3
--- count=0
--- standard ota
>>> wifi_config: Initializing WiFi config
>>> wifi_config: Found configuration, connecting to Clark
scandone
scandone
add 0
aid 15
cnt 

connected with Clark, channel 2
dhcp client start...
ip:192.168.1.133,mask:255.255.255.0,gw:192.168.1.1
>>> wifi_config: wifi_config_sta_connect_timeout_callback: Successfully connected
--- on_wifi_ready
--- ota_emergency?
--- ota_init
userbeta='0' otabeta='0'
rboot_config.unused[1]=LEDinfo from 0x00 to 0x00
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
Function called without core lock
--- ota_active_sector: 0xfa000
--- ota_set_verify...OFF
--- DNS: done!
--- ota_get_pubkey
 04 94 30 cc 5c 4e 50 29 15 ff 3d 41 da e9 e5 e3 64 27 b3 96 07 61 36 a4 83 28 4d fd f9 05 4f 0d 82 fa 57 26 06 b7 e8 1f 22 2d 2b 8a d2 ff 6e ac 59 73 00 b5 e4 9c 5f 68 ab 31 d3 9f ad bb 3d c8 4f 6d 38 e6 6f b8 b3 f7 22 21 b7 f2 e4 b7 75 ed 09 2c 87 2b 00 56 5b 81 e8 64 5c 2c 84 85 c0 3c 34
ret: 0
--- ota_get_privkey
--- ota_boot...0
--- ota_write_status
--- ota_load_user_app
user_repo='AchimPieters/ESP8266-HomeKit-Temperature-Humidity-Sensor' user_version='0.0.0' user_file='dht11_gpio4.bin'
--- ota_boot...0
--- ota_get_version
--- ota_connect LocalPort=dde6 DNS IP:140.82.114.3 local..OK remote..OK SSL..OK set_fd to github.com port 443..failed, return [-0x1]
wolfSSL_send error = -313
--- ota_boot...0
--- ota_compare 
Fatal exception (28): 
epc1=0x4000bdc8
epc2=0x00000000
epc3=0x40105f93
excvaddr=0x00000000
depc=0x00000000
excsave1=0x402186eb
Registers:
a0 402186eb a1 3fffab40 a2  00000000 a3  4023acfc
a4  00000001 a5  00000000 a6  0000007f a7  60000000
a8  00000011 a9  60000000 a10 60000000 a11 0000000a
a12 3fff15f4 a13 00000000 SAR 00000018

Stack: SP=0x3fffab40
0x3fffab40: 4023c7b3 00000002 b9a0e83e 40233a1c
0x3fffab50: 00000000 00000000 3fff15f4 40219c7d
0x3fffab60: 3fff2900 00000000 3fff68d8 4022c173
0x3fffab70: 3fffabb0 fffffffe 3fff15f4 4023acfc
0x3fffab80: 3fff29e8 00000000 3fff15f4 4021a07d
0x3fffab90: 20544547 6863412f 69506d69 72657465
0x3fffaba0: 53452f73 36323850 6f482d36 694b656d
0x3fffabb0: 65542d74 7265706d 72757461 75482d65

Free Heap: 26728

Free Heap: 26728
_heap_start 0x3fff2668 brk 0x3fffb118 supervisor sp 0x40000000 sp-brk 20200 bytes
arena (total_size) 35504 fordblks (free_size) 6528 uordblocks (used_size) 28976

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 2292, room 16 
tail 4
chksum 0x57
load 0x3ffe8000, len 772, room 4 
tail 0
chksum 0x0b
csum 0x0b

rBoot v1.4.0 - richardaburton@gmail.com
Flash Size:   8 Mbit
Flash Mode:   DOUT
Flash Speed:  40 MHz
rBoot Option: Big flash
rBoot Option: RTC data

Booting rom 0.
WA�l|$l���o�8��og�l'o��o�pg�rc�n|cn�dc`rlpp_task_hdl : 3ffefb28, prio:14, stack:512
pm_task_hdl : 3ffef590, prio:1, stack:176
frc2_timer_task_hdl:0x3fff47e8, prio:12, stack:200

ESP-Open-SDK ver: 0.0.1 compiled @ Feb  3 2021 22:37:20
phy ver: 273, pp ver: 8.3

**Comment by jmcjclark** [comment]
I figured this out. The instructions on the homepage has a link for LCM V2.1.2 otaboot.bin that is outdated and crashes. Downloaded and using latest version 2.2.5 and works great!

**Comment by AchimPieters** [comment]
@jmcjclark Indeed that is the solution, LCM has been adapted over time.
